CREATE OR ALTER PROC FI_SP_BuscarBeneficiario
	@Id BIGINT
AS
BEGIN
	IF(ISNULL(@Id,0) = 0)
		SELECT NOME, CPF, ID, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, ID, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END